export const getIt = (countryEng) => {
    const map = {
        "Afghanistan": "Afghanistan",
        "Angola": "Angola",
        "Albania": "Albania",
        "United Arab Emirates": "Emirati Arabi Uniti",
        "Argentina": "Argentina",
        "Armenia": "Armenia",
        "Antarctica": "Antartide",
        "French Southern and Antarctic Lands": "Terre australi e antartiche francesi",
        "Australia": "Australia",
        "Austria": "Austria",
        "Azerbaijan": "Azerbaigian",
        "Burundi": "Burundi",
        "Belgium": "Belgio",
        "Benin": "Benin",
        "Burkina Faso": "Burkina Faso",
        "Bangladesh": "Bangladesh",
        "Bulgaria": "Bulgaria",
        "Bahamas": "Bahamas",
        "Bosnia and Herzegovina": "Bosnia ed Erzegovina",
        "Belarus": "Bielorussia",
        "Belize": "Belize",
        "Bolivia": "Bolivia",
        "Brazil": "Brasile",
        "Brunei": "Brunei",
        "Bhutan": "Bhutan",
        "Botswana": "Botswana",
        "Central African Republic": "Repubblica Centrafricana",
        "Canada": "Canada",
        "Switzerland": "Svizzera",
        "Chile": "Cile",
        "China": "Cina",
        "Ivory Coast": "Costa d'Avorio",
        "Cameroon": "Camerun",
        "Democratic Republic of the Congo": "R.D. del Congo",
        "Republic of the Congo": "Congo",
        "Colombia": "Colombia",
        "Costa Rica": "Costa Rica",
        "Cuba": "Cuba",
        "Northern Cyprus": "Cipro del Nord",
        "Cyprus": "Cipro",
        "Czechia": "Repubblica Ceca",
        "Germany": "Germania",
        "Djibouti": "Gibuti",
        "Denmark": "Danimarca",
        "Dominican Republic": "Repubblica Dominicana",
        "Algeria": "Algeria",
        "Ecuador": "Ecuador",
        "Egypt": "Egitto",
        "Eritrea": "Eritrea",
        "Spain": "Spagna",
        "Estonia": "Estonia",
        "Ethiopia": "Etiopia",
        "Finland": "Finlandia",
        "Fiji": "Figi",
        "Falkland Islands": "Isole Falkland",
        "France": "Francia",
        "Gabon": "Gabon",
        "United Kingdom": "Regno Unito",
        "Georgia": "Georgia",
        "Ghana": "Ghana",
        "Guinea": "Guinea",
        "Gambia": "Gambia",
        "Guinea-Bissau": "Guinea-Bissau",
        "Equatorial Guinea": "Guinea Equatoriale",
        "Greece": "Grecia",
        "Greenland": "Groenlandia",
        "Guatemala": "Guatemala",
        "Guyana": "Guyana",
        "Honduras": "Honduras",
        "Croatia": "Croazia",
        "Haiti": "Haiti",
        "Hungary": "Ungheria",
        "Indonesia": "Indonesia",
        "India": "India",
        "Ireland": "Irlanda",
        "Iran": "Iran",
        "Iraq": "Iraq",
        "Iceland": "Islanda",
        "Israel": "Israele",
        "Italy": "Italia",
        "Jamaica": "Giamaica",
        "Jordan": "Giordania",
        "Japan": "Giappone",
        "Kazakhstan": "Kazakistan",
        "Kenya": "Kenya",
        "Kyrgyzstan": "Kirghizistan",
        "Cambodia": "Cambogia",
        "South Korea": "Corea del Sud",
        "Kosovo": "Kosovo",
        "Kuwait": "Kuwait",
        "Laos": "Laos",
        "Lebanon": "Libano",
        "Liberia": "Liberia",
        "Libya": "Libia",
        "Sri Lanka": "Sri Lanka",
        "Lesotho": "Lesotho",
        "Lithuania": "Lituania",
        "Luxembourg": "Lussemburgo",
        "Latvia": "Lettonia",
        "Morocco": "Marocco",
        "Moldova": "Moldavia",
        "Madagascar": "Madagascar",
        "Mexico": "Messico",
        "Macedonia": "Macedonia del Nord",
        "Mali": "Mali",
        "Myanmar": "Birmania",
        "Montenegro": "Montenegro",
        "Mongolia": "Mongolia",
        "Mozambique": "Mozambico",
        "Mauritania": "Mauritania",
        "Malawi": "Malawi",
        "Malaysia": "Malesia",
        "Namibia": "Namibia",
        "New Caledonia": "Nuova Caledonia",
        "Niger": "Niger",
        "Nigeria": "Nigeria",
        "Nicaragua": "Nicaragua",
        "Netherlands": "Paesi Bassi",
        "Norway": "Norvegia",
        "Nepal": "Nepal",
        "New Zealand": "Nuova Zelanda",
        "Oman": "Oman",
        "Pakistan": "Pakistan",
        "Panama": "Panama",
        "Peru": "Perù",
        "Philippines": "Filippine",
        "Papua New Guinea": "Papua Nuova Guinea",
        "Poland": "Polonia",
        "Puerto Rico": "Porto Rico",
        "North Korea": "Corea del Nord",
        "Portugal": "Portogallo",
        "Paraguay": "Paraguay",
        "Qatar": "Qatar",
        "Romania": "Romania",
        "Russia": "Russia",
        "Rwanda": "Ruanda",
        "Western Sahara": "Sahara Occidentale",
        "Saudi Arabia": "Arabia Saudita",
        "Sudan": "Sudan",
        "South Sudan": "Sud Sudan",
        "Senegal": "Senegal",
        "Solomon Islands": "Isole Salomone",
        "Sierra Leone": "Sierra Leone",
        "El Salvador": "El Salvador",
        "Somaliland": "Somaliland",
        "Somalia": "Somalia",
        "Republic of Serbia": "Serbia",
        "Suriname": "Suriname",
        "Slovakia": "Slovacchia",
        "Slovenia": "Slovenia",
        "Sweden": "Svezia",
        "Swaziland": "Eswatini",
        "Syria": "Siria",
        "Chad": "Ciad",
        "Togo": "Togo",
        "Thailand": "Tailandia",
        "Tajikistan": "Tagikistan",
        "Turkmenistan": "Turkmenistan",
        "East Timor": "Timor Est",
        "Trinidad and Tobago": "Trinidad e Tobago",
        "Tunisia": "Tunisia",
        "Turkey": "Turchia",
        "Taiwan": "Taiwan",
        "United Republic of Tanzania": "Tanzania",
        "Uganda": "Uganda",
        "Ukraine": "Ucraina",
        "Uruguay": "Uruguay",
        "United States of America": "Stati Uniti d'America",
        "Uzbekistan": "Uzbekistan",
        "Venezuela": "Venezuela",
        "Vietnam": "Vietnam",
        "Vanuatu": "Vanuatu",
        "Yemen": "Yemen",
        "South Africa": "Sudafrica",
        "Zambia": "Zambia",
        "Zimbabwe": "Zimbabwe"
    };

    return map[countryEng] || countryEng;
};

export const getApiCountryName = (countryEng) => {
    const apiMap = {
        "United States of America": "United States",
        "Democratic Republic of the Congo": "Congo Democratic Republic",
        "Republic of Serbia": "Serbia",
        "United Republic of Tanzania": "Tanzania",
        "Republic of the Congo": "Congo",
        "Czechia": "Czech Republic",
        "Guinea-Bissau": "Guinea Bissau",
        "Moldova": "Moldova, Republic of",
        "Ivory Coast": "Cote d'Ivoire",
        "Gambia": "The Gambia",
        "Bahamas": "The Bahamas"
    };
    return apiMap[countryEng] || countryEng;
};
